name: poc_http_https
description: "PoC to validate http and https requests on Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
